version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/build
    overwrite: yes
    file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: scripts/after-deploy.sh
      runas: ubuntu
